/**
 * AI Tips Card Component
 * Displays AI-powered farming tips with loading and error states
 */
import React from 'react';
import { Sparkles, RefreshCw, AlertCircle } from 'lucide-react';

/**
 * Skeleton loader for tips
 */
const TipsSkeleton = () => (
  <div className="space-y-3 animate-pulse">
    {[1, 2, 3, 4].map((i) => (
      <div key={i} className="flex items-start gap-2">
        <div className="w-2 h-2 mt-2 rounded-full bg-yellow-300/60 shrink-0" />
        <div className="flex-1 space-y-2">
          <div 
            className="h-4 bg-yellow-300/40 rounded" 
            style={{ width: `${85 - (i * 10)}%` }}
          />
        </div>
      </div>
    ))}
    <div className="flex items-center gap-2 pt-2">
      <Sparkles size={14} className="text-yellow-500/50 animate-pulse" />
      <span className="text-xs text-yellow-600/60">Generating tips with AI...</span>
    </div>
  </div>
);

/**
 * Error state component
 */
const ErrorState = ({ onRetry }) => (
  <div className="flex flex-col items-center justify-center py-4 text-yellow-700">
    <AlertCircle size={24} className="mb-2 text-yellow-600" />
    <p className="text-sm mb-3">Unable to generate tips right now</p>
    {onRetry && (
      <button
        onClick={onRetry}
        className="flex items-center gap-2 px-3 py-1.5 text-xs font-medium bg-yellow-200 hover:bg-yellow-300 rounded-lg transition-colors"
      >
        <RefreshCw size={14} />
        Try Again
      </button>
    )}
  </div>
);

/**
 * AI Tips Card
 * @param {Object} props
 * @param {string[]} props.tips - Array of tip strings
 * @param {boolean} props.isLoading - Loading state
 * @param {boolean} props.isError - Error state
 * @param {string} props.source - Source of tips (openai, groq, anthropic, static)
 * @param {Function} props.onRetry - Retry callback
 */
const AiTipsCard = ({ 
  tips = [], 
  isLoading = false, 
  isError = false, 
  source,
  onRetry 
}) => {
  // Only show skeleton on initial load (no cached tips)
  const showSkeleton = isLoading && tips.length === 0;
  // Only show error if we have no tips to display
  const showError = isError && tips.length === 0;
  // Show tips if we have any (even while refreshing)
  const showTips = tips.length > 0;
  // Show subtle loading indicator when refreshing with existing tips
  const isRefreshing = isLoading && tips.length > 0;

  return (
    <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-5 transition-all duration-300">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-yellow-800 flex items-center gap-2">
          <span>🌾</span>
          <span>AI Farming Tips</span>
          {source && source !== 'static' && (
            <Sparkles size={16} className="text-yellow-600" />
          )}
          {isRefreshing && (
            <span className="text-xs font-normal text-yellow-600 animate-pulse">updating...</span>
          )}
        </h3>
        
        {onRetry && (
          <button
            onClick={onRetry}
            disabled={isLoading}
            className="p-2 text-yellow-600 hover:text-yellow-800 hover:bg-yellow-100 rounded-lg transition-colors disabled:opacity-50"
            title="Refresh tips"
          >
            <RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} />
          </button>
        )}
      </div>

      {/* Content */}
      {showSkeleton && <TipsSkeleton />}
      
      {showError && <ErrorState onRetry={onRetry} />}
      
      {showTips && (
        <ul className="space-y-2.5">
          {tips.map((tip, index) => (
            <li 
              key={index}
              className="flex items-start gap-2 text-yellow-700 text-sm leading-relaxed animate-fadeIn"
              style={{ 
                animationDelay: `${index * 100}ms`,
                animationFillMode: 'both'
              }}
            >
              <span className="text-yellow-500 mt-0.5 shrink-0">•</span>
              <span>{tip}</span>
            </li>
          ))}
        </ul>
      )}

      {/* Footer */}
      {showTips && (
        <div className="flex items-center gap-2 mt-4 pt-3 border-t border-yellow-200/50">
          {source && source !== 'static' ? (
            <>
              <Sparkles size={12} className="text-yellow-500" />
              <span className="text-xs text-yellow-600">
                Generated by AI • Personalized for your location and conditions
              </span>
            </>
          ) : (
            <span className="text-xs text-yellow-600">
              Based on current weather conditions
            </span>
          )}
        </div>
      )}
    </div>
  );
};

export default AiTipsCard;

